### ISSUE TITLE
Tripod Mount Dimensions

### ISSUE THREAD

**Issue by nlapenn** [idcrook/psychic-winner#1]
The tripod mount is 7.62 where it connects to the ring, however, the lower section, starting right below the circuit board is 11.43 (on your tech diagram - the official diagram marks width but doesn't give a number).   11.43 seems right since its not actually deep enough to line up with the bottom of the circuit board as it appears in the diagram.
![pimount](https://user-images.githubusercontent.com/57019362/81609014-25209280-93a5-11ea-8fc1-819ac0a6fc0d.PNG)

**Comment by idcrook** [comment]
I **think** I addressed this in https://github.com/idcrook/psychic-winner/commit/a06cf88330e681900f5a2f778243d4117738f791 back in July (after noticing it mentioned in comments on [Raspberry Pi HQ Camera Reference Model with 6mm Wide Angle and 16mm Telephoto Lens models by dpc - Thingiverse](https://www.thingiverse.com/thing:4335497) )

Related [comment in thread on Thingiverse object](https://www.thingiverse.com/thing:4335497/comments#comment-3566403)
